### ISSUE TITLE
"Bus error (core dumped)" when trying to run Produce example

### ISSUE THREAD

**Issue by shades198** [nmred/kafka-php#10]
I ran Produce.php in the example directory and it's dying after throwing "Bus error (core dumped)" message. Code that I have downloaded is unaltered except in ZooKeeper.php constructor where it was found to be Zookeeper instead of ZooKeeper so there was autoload error. I corrected it and now this error is coming

**Comment by nmred** [comment]
hi

can you detailed description which error? I guess too many connections , but this lib library has  long connection

**Comment by shades198** [comment]
That's all the error that comes. Where can I find any additional debugging info?

**Comment by nmred** [comment]
You can first test Zookeeper, ensure zookeeper can connect

**Comment by shades198** [comment]
Means? Test zookeeper client? Actually the problem lies there itself. In the constructor of zookeeper the script dies. 
```
    public function __construct($hostList, $timeout = null)
    {
        if (!is_null($timeout) && is_numeric($timeout)) {
	  echo ">>>";
            $this->zookeeper = new \Kafka\ZooKeeper($hostList, null, $timeout);
        } else {
            $this->zookeeper = new \Kafka\ZooKeeper($hostList);
        }
    }
```

Above is the constructor of zookeeper found in src/kafka directory. String ">>>" is echoed out and then Bus error comes

**Comment by nmred** [comment]
I think you zookeeper server has max connection limits,  Try run simply zookeeper client  script test it, 
 first make sure your environment can be normal connection zookeeper
<?php 
try {
     $zoo = new \Zookeeper($hostList);
} catch (Exception $e) {
     var_dump($e);
}

**Comment by shades198** [comment]
I appended above code in src/Kafka/ZooKeeper.php class. But it's giving me a fatal error 'Zookeeper not found'. So I corrected the name to ZooKeeper. But it's giving me the same error

**Comment by nmred** [comment]
you sure installed zookeeper client extension? 

run `php -m |grep zookeeper` have zookeeper?

**Comment by shades198** [comment]
But in the readme it was given that zookeeper client extension is required only in the case of zookeeper based consumer. I only want producer in php as our application is running on java at the backend

**Comment by shades198** [comment]
After installing zookeeper extension for php, error seems to have gone. My apology for posting a non-issue. However, I will request you to remove the line saying zookeeper extension is required for zookeeper based consumer. It might cause confusion. Thanks for help :)
