### ISSUE TITLE
getting a zookeeper error when producing

### ISSUE THREAD

**Issue by warroyo** [nmred/kafka-php#12]
I am receiving the following error when producing to kafka using the zookeeper method. Is there a way to close the connection to zookeeper? I am making multiple call to the function below and it seems to be trying to hold the connections open.

            $rand = rand(0, 130);
            $producer = \Kafka\Produce::getInstance('zookeeper-host', 3000);
            $producer->setRequireAck(1);
            $producer->setMessages('topic', $rand, $message);
            $result = $producer->send();

Here is the error i am getting constantly.It eventually causes my code to stop running.

2015-04-22 20:04:11,185:5586(0x7f502b936700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 13ms

**Comment by nmred** [comment]
Hi

You can reference http://mail-archives.apache.org/mod_mbox/zookeeper-user/201205.mbox/%3CCANLc_9J4-cUb3LhPf94ZogYhOz9KhXko7jke4qaDDgL6uo=r=Q@mail.gmail.com%3E

**Comment by Timandes** [comment]
Try C client in zookeeper-3.5.0alpha.

See: 
    https://issues.apache.org/jira/browse/ZOOKEEPER-642
