### ISSUE TITLE
Produce::getInstance() ignores arguments

### ISSUE THREAD

**Issue by bobrik** [nmred/kafka-php#13]
After first initialization arguments for `Produce::getInstance()` are silently ignored. This way you cannot use more than one kafka cluster. Is there a reason for this?

```php
$ProducerOne = new Producer($someHosts, $timeout);
$ProducerTwo = new Producer($otherHosts, $timeout);
```

This way it is more flexible, users would cache `Producer` instance if they want to.

**Comment by Timandes** [comment]
It's much better when running long-term CLI programmes.

**Comment by nmred** [comment]
Yeah, can consider to cancel creating singleton restrictions.

```

public function __construct()

instead of
 
private function __construct()

```

but if only one kafka cluster using the default `Produce::getInstance() ` get Instance recommendation

**Comment by nmred** [comment]
Done!

**Comment by Timandes** [comment]
Z-AN, Zan!
