### ISSUE TITLE
Ack'ing messages

### ISSUE THREAD

**Issue by pushpesh4u** [nmred/kafka-php#15]
Hello,

How do I ack messages while consuming so that the server can remove them from the queue.

Also, is there a way to detect any errors while publishing the messages so that we can take actions, such as storing the message in a DB, when an error in publishing occurs.

**Comment by Timandes** [comment]
From return value of `Produce::send()`?
Maybe the comments are not right.
It seems that `Produce::send()` returns an assoc-array.

**Comment by pushpesh4u** [comment]
This is the response from `Produce::send()`

```
            [0] => Array
                (
                    [errCode] => 0
                    [offset] => 127
                )
```

If I am sending in a batch, the response does not indicate if any of those messages failed, so that I can log that message to be processed later.

**Comment by Timandes** [comment]
After i run this:

    <?php

    include_once 'bootstrap.php';

    $producer = \Kafka\Produce::getInstance('localhost:2181', 3000);

    $producer->setRequireAck(-1);
    $producer->setMessages('test', 0, array('foo001','foo002'));
    $r = $producer->send();
    var_dump($r);

I got response:

    array(1) {
      'test' =>
      array(1) {
        [0] =>
        array(2) {
          'errCode' =>
          int(0)
          'offset' =>
          int(7)
        }
      }
    }

`test` is the `topic name`. 
`0` is `partition id`.

Based on `Decoder::produceResponse()`, only the response of the last message belonged to which were sent to the same partition will be returned.

**Comment by Timandes** [comment]
It seems that `Produce::send()` (line 221) will never be run.

**Comment by nmred** [comment]
@pushpesh4u you can use `Produce:: setRequireAck()`  method set ack mode.

     * This field indicates how many acknowledgements the servers should receive
     * before responding to the request. If it is 0 the server will not send any
     * response (this is the only case where the server will not reply to a
     * request). If it is 1, the server will wait the data is written to the
     * local log before sending a response. If it is -1 the server will block
     * until the message is committed by all in sync replicas before sending a
     * response. For any number > 1 the server will block waiting for this
     * number of acknowledgements to occur (but the server will never wait for
     * more acknowledgements than there are in-sync replicas).

**Comment by nmred** [comment]
@Timandes  

What does it mean, can you  detailed description?  thanks.

>> It seems that Produce::send() (line 221) will never be run.

**Comment by Timandes** [comment]
@nmred 

Sorry, i've not noticed the outer `foreach`.

But i think `array_merge` will destroy the structure of the `$responseData[$topicName]`.

Try this test code:

    <?php

    $info = array(
            0 => array(
                    'errCode' => 0,
                    'offset' => 7,
                ),
        );
    $topicName = 'test';

    $responseData[$topicName] = $info;

    $info[0]['offset'] = 8;
    $responseData[$topicName] = array_merge($info, $responseData[$topicName]);

    var_dump($responseData);

Result:

    array(1) {
      'test' =>
      array(2) {
        [0] =>
        array(2) {
          'errCode' =>
          int(0)
          'offset' =>
          int(8)
        }
        [1] =>
        array(2) {
          'errCode' =>
          int(0)
          'offset' =>
          int(7)
        }
      }
    }

The first message sent to partition 0 will be treated as message that was sent to partition 1 by mistake.

**Comment by nmred** [comment]
$info variable is assoc-array,  array key is current topic partition id, this id typeof int and unique, will not destroy the structure

**Comment by slavash** [comment]
@nmred If I understand question correctly @pushpesh4u wants to remove consumed messages from the queue. So the question relates to offset API. I have same problem with consumer - the last message consumed in loop until new message sent to the topic.
  I didn't find the way to enable auto_commit... probably I have to sent offsetCommit manually? Can you clarify the issue please. 

Consumer code:
```
$consumer = Consumer::getInstance('192.168.56.111:2181');

    $consumer->setFromOffset(true);
    $consumer->setOffsetStrategy(Offset::DEFAULT_LAST);

    $consumer->setGroup('demo_group');
    $consumer->setPartition('demo_topik', 0, Offset::DEFAULT_LAST);

    $consumer->setTopic('demo_topik');

    $result = $consumer->fetch();
    /**
     * @var string $topicName
     * @var  Partition $partition
     */
    foreach ($result as $topicName => $partition) {
        /**
         * @var  int $partId
         * @var  $messageSet
         */
        foreach ($partition as $partId => $messageSet) {

            $highOffset = $partition->getHighOffset();
            echo 'HighOffset: ' . $highOffset . PHP_EOL;
            foreach ($messageSet as $message) {
                echo $message . PHP_EOL;
            }

            $offset = $partition->getMessageOffset();
            echo 'MessageOffset: ' . $offset . PHP_EOL;

           //  $partition->setMessageOffset(++$highOffset);   ????

        }
    }

    sleep(1);
}
```

**Comment by smallwalk** [comment]
@slavash  I met the same problem.

file:Kafka\Protocol\Fetch\Helper\CommitOffset on line 114

$offsetObject->setOffset($offset); //wrong

$offsetObject->setOffset($offset + 1); //correct

**Comment by lalitktechfour** [comment]
Not able to install zookeper class in local window..
Produce working fine but not able to consume in php...

Getting error:
 Uncaught exception 'RuntimeException' with message 'ZooKeeper not found' in C:\xampp\htdocs\kafka\code\autoloader.php:38 Stack trace: #0 [internal function]: {closure}('ZooKeeper') #1 C:\xampp\htdocs\kafka\src\Kafka\ZooKeeper.php(103): spl_autoload_call('ZooKeeper') #2 C:\xampp\htdocs\kafka\src\Kafka\Consumer.php(121): Kafka\ZooKeeper->__construct('localhost:2181', NULL) #3 C:\xampp\htdocs\kafka\src\Kafka\Consumer.php(103): Kafka\Consumer->__construct('localhost:2181', NULL) #4 C:\xampp\htdocs\kafka\code\Consumer_test.php(39): Kafka\Consumer::getInstance('localhost:2181') #5 {main}



Please suggest..

**Comment by nmred** [comment]
@lalitktechfour  consume must use zookeeper ext support

**Comment by lalitktechfour** [comment]
So how can i install zookeeper ext in window (xampp) ?

**Comment by Timandes** [comment]
@lalitktechfour There is no Windows version for `php-zookeeper` ...
