### ISSUE TITLE
Huge delay while sending the message from producer

### ISSUE THREAD

**Issue by shades198** [nmred/kafka-php#17]
I was profiling producer code and found that `producer->send()` was taking more than 30 ms even on localhost! When I dug up a little I found that `$this->zookeeper->getPartitionState($topicName, $partitionId);` in src/Kafka/Client.php in function name `getHostByPartition`. This line of code was taking almost all of that time. The application I am working with cannot  accept a delay of 5-10 ms more. Is there any workaround for this?

**Comment by davidsheldon** [comment]
Can you use the new non-Zookeeper producer? Pass the Kafka broker(s) as the last parameter of the constructor, rather than the Zookeeper hosts as the first.

e.g. `$this->producer = new Produce(null, null, $kafkaBrokers);`
