### ISSUE TITLE
fwrite randomly fails in Socket

### ISSUE THREAD

**Issue by tolejarz** [nmred/kafka-php#24]
Hi,

I'm trying to send 30 000 messages to Kafka and sometimes fwrite fails with message:

    PHP Notice:  fwrite(): send of 8192 bytes failed with errno=11 Resource temporarily unavailable in /test/vendor/nmred/kafka-php/src/Kafka/Socket.php on line 296

It's just a Notice, loop continues until `$written` reaches `$buflen` and all is written. But this notice is ugly and should be correctly handled. However, I don't understand why it happens "sometimes"...

**Comment by nmred** [comment]
@tolejarz  errno=11 is  socket report EAGAIN error that  on nonblock pipes TCP buffer  fully, this error should continue write

**Comment by nmred** [comment]
Fixed !
