### ISSUE TITLE
Fatal error: Class 'ZooKeeper' not found

### ISSUE THREAD

**Issue by pctin** [nmred/kafka-php#26]
Hi,

I have problem when integrating with yii project, can you please check:
Fatal error: Class 'ZooKeeper' not found in:
\protected\vendors\kafka-php-master\src\Kafka\ZooKeeper.php on line 92

Here is the code: 
        Yii::import('application.vendors.kafka-php-master.example.*');
        require_once 'autoloader.php';
        $produce = \Kafka\Produce::getInstance('localhost:2181', 3000);
	$produce->setRequireAck(-1);
        $produce->setMessages('test', 0, array('test1111111'));
        $result = $produce->send();
        var_dump($result);

**Comment by Timandes** [comment]
This project requires PHP Zookeeper Extension (https://github.com/andreiz/php-zookeeper).

**Comment by pctin** [comment]
Thank you!

I have not thought that I have to install PHP Zookeeper Extension:
"The PHP Zookeeper extension is required if you want to use the Zookeeper-based consumer.
Productor can not dependency zookeeper"

**Comment by Timandes** [comment]
Please close the issue then.

**Comment by nmred** [comment]
@pctin  if you want use zookeeper extension you can refer to https://github.com/nmred/kafka-php/blob/master/example/ProduceWithoutZooKeeper.php

**Comment by pctin** [comment]
That's so helpful, I got it, thank you, good guys!

I closed issue also.
