### ISSUE TITLE
Consumer example failed

### ISSUE THREAD

**Issue by Surfoo** [nmred/kafka-php#33]
Hello,

I tried to execute example/Consumer.php, but the autoloader failed to include ZooKeeper.php:

    $ php Consumer.php
    PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'ZooKeeper not found' in /tmp/kafka-php/example/autoloader.php:39
    Stack trace:
    #0 [internal function]: {closure}('ZooKeeper')
    #1 /tmp/kafka-php/src/Kafka/ZooKeeper.php(94): spl_autoload_call('ZooKeeper')
    #2 /tmp/kafka-php/src/Kafka/Consumer.php(134): Kafka\ZooKeeper->__construct('172.31.63.176:2...', NULL)
    #3 /tmp/kafka-php/src/Kafka/Consumer.php(117): Kafka\Consumer->__construct('172.31.63.176:2...', NULL)
    #4 /tmp/kafka-php/example/Consumer.php(4): Kafka\Consumer::getInstance('172.31.63.176:2...')
    #5 {main}
      thrown in /tmp/kafka-php/example/autoloader.php on line 39

**Comment by Timandes** [comment]
See: #26

**Comment by Surfoo** [comment]
thanks, it works!
