### ISSUE TITLE
还不能用在正式环境？

### ISSUE THREAD

**Issue by wenjun1055** [nmred/kafka-php#34]

**Comment by Crim** [comment]
这个已经在我们的正式环境用了六个月。 没有问题。我们传送数据利用这个。
http://imgur.com/a/OoTx6

**Comment by w3hacker** [comment]
holyhigh

**Comment by luxixing** [comment]
请问此客户端支持 kafka_2.11-0.9.0.0 吗
kafka_2.11-0.9.0.0 现在是最新发布版本
谢谢

**Comment by nmred** [comment]
@luxixing 对于broker0.9.x 版本生产者api是兼容的，消费者目前没有测试过。。

**Comment by luxixing** [comment]
@nmred  我们这边正好是消费者
由其他部门生产数据，PHP 去消费者数据
如果我们用这个扩展，怎么去测试消费者是否兼容0.9？
或者您有没有计划直接支持0.9呀

**Comment by nmred** [comment]
@luxixing 消费者的协议0.9和0.8 不太一样，如果支持0.9需要重新实现，目前还没有时间更新，有时间的话会支持的，你暂且可以测试用0.8协议来读取

**Comment by luxixing** [comment]
@nmred  好的，期待早日支持
