### ISSUE TITLE
set old offset 

### ISSUE THREAD

**Issue by smallwalk** [nmred/kafka-php#39]
file:Kafka\Protocol\Fetch\Helper\CommitOffset on line 114

$offsetObject->setOffset($offset); //wrong

$offsetObject->setOffset($offset + 1); //correct

**Comment by GOOD21** [comment]
我也遇到了这个问题，始终多取了一条出来，但是这个bug这么明显，感觉不像bug。。。

**Comment by smallwalk** [comment]
@GOOD21  同感
