### ISSUE TITLE
kafka_2.11-0.9.0.0 支持

### ISSUE THREAD

**Issue by luxixing** [nmred/kafka-php#55]
Hi，我们这边的kafka_版本信息如下

> kafka_2.11-0.9.0.0
zookeeper-3.4.6
PHP 5.5.25 (cli) (built: May 20 2015 07:30:18) 

请问此扩展现在支持么
谢谢

**Comment by nmred** [comment]
@luxixing  当前版本对于生产者API是支持 v0.9.x 的，消费者API正在开发
