### ISSUE TITLE
Cached broker list causes issues when a broker drops in/out of a cluster

### ISSUE THREAD

**Issue by Crim** [nmred/kafka-php#57]
Using the [Zookeeper metadata](https://github.com/nmred/kafka-php/blob/master/src/Kafka/ZooKeeper.php), the topic partition metadata is *not* cached, but [Client.php](https://github.com/nmred/kafka-php/blob/master/src/Kafka/Client.php#L158) *does* cache the broker list.  

So now imagine the following scenario:
You have a 3 node cluster, replica factor of 3.  You bring down one node in the cluster.  So you now have 2 brokers.  You fire up a long running php script that publishes to this cluster.  At this point all of the metadata (brokers and partitions) are consistent with eachother.  Now while this long running php script continues to run, you bring back up the 3rd broker.  What happens now is your cached broker list only shows brokers 1 and 2, but your partition metadata will return broker 3 for the topics/partitions its assumed leadership for.

Since the [Kafka Metadata](https://github.com/nmred/kafka-php/blob/master/src/Kafka/MetaDataFromKafka.php) instance caches both broker list and topic partition metadata, I believe it also suffers from a similar issue if leaders are shifted around within the cluster during the lifetime of the process.

Inbound PR that should solve this issue.

**Comment by Crim** [comment]
Take a look at PR https://github.com/nmred/kafka-php/pull/58 I believe it solves this issue by adding a [refreshMetadata](https://github.com/Crim/kafka-php/blob/sp/RefreshMetadata/src/Kafka/ClusterMetaData.php#L57) method on the ClusterMetaData interface.

In [Client.php](https://github.com/Crim/kafka-php/blob/sp/RefreshMetadata/src/Kafka/Client.php#L148) I've removed caching the broker list.  I've modified [ZooKeeper](https://github.com/Crim/kafka-php/blob/sp/RefreshMetadata/src/Kafka/ZooKeeper.php#L116) to now cache the broker list instead. [MetadataFromKafka](https://github.com/Crim/kafka-php/blob/sp/RefreshMetadata/src/Kafka/MetaDataFromKafka.php#L109) already is keeping a cache of the broker list.  

In [Client.getHostByPartition](https://github.com/Crim/kafka-php/blob/sp/RefreshMetadata/src/Kafka/Client.php#L174) I've added the ability to attempt refreshing the metadata once before failing.

I believe this should solve the issue for both metadata classes.

**Comment by nmred** [comment]
Already merged, Thanks @Crim
