### ISSUE TITLE
Server side disconnect can cause library to go into infinite loop when producing

### ISSUE THREAD

**Issue by Crim** [nmred/kafka-php#59]
So I've noticed this after upgrading to Kafka 0.9.0.0, but I believe this problem exists with 0.8.x brokers if the server closes the clients connection.

Kafka 0.9.0.0 introduces a new configuration property on the broker called connections.max.idle.ms defined as: Idle connections timeout: the server socket processor threads close the connections that idle more than this.  By default the timeout is 10 minutes.

If you connect a producer using this library to a 0.9.0.0 broker, and the client exceeds this idle timeout, and then goes to publish, it will get stuck in an infinite loop trying to fwrite the now dead stream.  You'll get warnings like this repeated:

PHP Notice:  fwrite(): send of 4096 bytes failed with errno=32 Broken pipe in /path/vendor/nmred/kafka-php/src/Kafka/Socket.php on line 358

PHP's fwrite() is great (sarcasm) in that it will return 0 when you attempt to fwrite a stream that has been closed by the server.  Additionally stream_select() will continue to say that the stream is available to write.  As far as I can tell, there is no reliable way to determine if the stream has been closed by the server.  The only 'best practice' I can find online for this is to set a limit on how many write retries to allow when 0 bytes are written.

**Comment by Crim** [comment]
Possible solution in https://github.com/nmred/kafka-php/pull/60 

Anyone have any other possible solutions?

**Comment by git-hulk** [comment]
Php offer php_stream_eof to check whether local socket is alive by using system call poll. It would work well at this condition.
