### ISSUE TITLE
error when not specifying the offset

### ISSUE THREAD

**Issue by warroyo** [nmred/kafka-php#6]
I am recieving the following error when not specifying the offset while consuming.

`Unexpected EOF while reading 4 bytes from stream (no data)` 

this is in the following function:

```
 public function fetchOffsetResponse()
    {
        $result = array();
        $dataLen = self::unpack(self::BIT_B32, $this->stream->read(4, true));
        $dataLen = array_shift($dataLen);
```

I have also tried specifying an offset but no data seems to be returned from the topic. is there a specific option for the offset to return the latest data?

I believe that you can fetch the current offset from kafka and have it handle the offsets. you should only need to specify whether you want the beginning or end offset.

**Comment by nmred** [comment]
default read newest message
